# **Exploratory Data Analysis**

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline
from matplotlib import font_manager, rc
import matplotlib
matplotlib.rcParams['font.family'] = 'Malgun Gothic'
matplotlib.rcParams['axes.unicode_minus'] = False
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')
# pd.set_option('display.max_rows', None)

In [2]:
retail = pd.read_csv('GS.csv')

retail.head()

,ADR1,ADR2,CATE1,CATE2,2021-01-01,2021-01-02,2021-01-03,2021-01-04,2021-01-05,2021-01-06,...,2021-03-22,2021-03-23,2021-03-24,2021-03-25,2021-03-26,2021-03-27,2021-03-28,2021-03-29,2021-03-30,2021-03-31
0,군산시,개정동,10,식사,0.309,0.448,0.346,0.470,0.572,0.591,...,0.460,0.652,0.416,0.715,0.434,0.402,0.354,0.451,0.451,0.453
1,군산시,개정동,20,간식,0.255,0.178,0.303,0.165,0.105,0.166,...,0.194,0.124,0.140,0.089,0.084,0.177,0.164,0.206,0.225,0.180
2,군산시,개정동,30,마실거리,0.582,0.584,0.575,0.602,0.558,0.478,...,0.578,0.462,0.666,0.439,0.711,0.581,0.648,0.552,0.549,0.599
3,군산시,개정동,40,홈&리빙,0.013,0.002,0.031,0.005,0.019,0.010,...,0.016,0.002,0.006,0.006,0.019,0.040,0.020,0.006,0.006,0.012
4,군산시,개정동,50,헬스&뷰티,0.041,0.047,0.005,0.017,0.007,0.014,...,0.007,0.020,0.027,0.011,0.013,0.048,0.034,0.016,0.015,0.011

In [3]:
retail = retail.transpose()

retail.head()

,0,1,2,3,4,5,6,7,8,9,...,80,81,82,83,84,85,86,87,88,89
ADR1,군산시,군산시,군산시,군산시,군산시,군산시,군산시,군산시,군산시,군산시,...,군산시,군산시,군산시,군산시,군산시,군산시,군산시,군산시,군산시,군산시
ADR2,개정동,개정동,개정동,개정동,개정동,개정동,경암동,경암동,경암동,경암동,...,조촌동,조촌동,조촌동,조촌동,흥남동,흥남동,흥남동,흥남동,흥남동,흥남동
CATE1,10,20,30,40,50,60,10,20,30,40,...,30,40,50,60,10,20,30,40,50,60
CATE2,식사,간식,마실거리,홈&리빙,헬스&뷰티,취미&여가활동,식사,간식,마실거리,홈&리빙,...,마실거리,홈&리빙,헬스&뷰티,취미&여가활동,식사,간식,마실거리,홈&리빙,헬스&뷰티,취미&여가활동
2021-01-01,0.309,0.255,0.582,0.013,0.041,0.059,0.523,0.144,0.494,0.016,...,0.511,0.021,0.044,0.04,0.405,0.647,0.839,0.032,0.116,0.015

In [4]:
retail = retail[4:]

retail

,0,1,2,3,4,5,6,7,8,9,...,80,81,82,83,84,85,86,87,88,89
2021-01-01,0.309,0.255,0.582,0.013,0.041,0.059,0.523,0.144,0.494,0.016,...,0.511,0.021,0.044,0.04,0.405,0.647,0.839,0.032,0.116,0.015
2021-01-02,0.448,0.178,0.584,0.002,0.047,0.0,0.432,0.244,0.512,0.014,...,0.584,0.02,0.045,0.052,0.443,0.674,0.806,0.079,0.043,0.009
2021-01-03,0.346,0.303,0.575,0.031,0.005,0.0,0.466,0.119,0.543,0.013,...,0.565,0.014,0.022,0.045,0.45,0.563,0.892,0.038,0.061,0.049
2021-01-04,0.47,0.165,0.602,0.005,0.017,0.0,0.473,0.126,0.615,0.001,...,0.549,0.023,0.051,0.025,0.618,0.411,0.855,0.041,0.101,0.028
2021-01-05,0.572,0.105,0.558,0.019,0.007,0.0,0.615,0.157,0.435,0.054,...,0.538,0.022,0.031,0.029,0.709,0.419,0.845,0.019,0.009,0.053
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-03-27,0.402,0.177,0.581,0.04,0.048,0.012,0.452,0.14,0.486,0.062,...,0.562,0.074,0.048,0.021,0.624,0.419,0.852,0.1,0.035,0.022
2021-03-28,0.354,0.164,0.648,0.02,0.034,0.04,0.513,0.234,0.43,0.012,...,0.583,0.022,0.04,0.02,0.453,0.5,0.997,0.043,0.062,0.0
2021-03-29,0.451,0.206,0.552,0.006,0.016,0.029,0.587,0.168,0.458,0.036,...,0.601,0.015,0.029,0.024,0.567,0.605,0.858,0.013,0.007,0.003
2021-03-30,0.451,0.225,0.549,0.006,0.015,0.013,0.471,0.152,0.584,0.005,...,0.635,0.019,0.038,0.012,0.584,0.432,0.912,0.048,0.045,0.033
2021-03-31,0.453,0.18,0.599,0.012,0.011,0.005,0.493,0.136,0.601,0.01,...,0.607,0.024,0.038,0.025,0.485,0.381,1.131,0.014,0.031,0.011

In [5]:
# # 에러
# sns.lineplot(data=retail, x=retail.index, y=retail[0])
# plt.show()